replicaCount: 2

image:
  repository: fastapi-stage2
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

app:
  name: fastapi
  environment: production

redis:
  host: redis
  port: 6379
  database: "0"
  existingSecret: redis-secret
  existingSecretKey: REDIS_PASSWORD
  password: "CHANGE-ME"
  image: redis:7-alpine
  persistence:
    size: 1Gi
    accessMode: ReadWriteOnce

secret:
  appSecret: "CHANGE-ME"

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: true
  className: nginx
  host: fastapi-stage9.local
  path: /api(/|$)(.*)
  pathType: ImplementationSpecific
