apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Values.app.name }}
data:
  APP_NAME: "{{ .Values.app.name }}"
  ENVIRONMENT: "{{ .Values.app.environment }}"
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
